### ISSUE TITLE
Provide sandboxing example

### ISSUE THREAD

**Issue by emesare** [rhaiscript/rhai-fs#4]
For security and compatibility, it would be a good idea to provide a read-to-go example on how to show how to sandbox `rhai-fs`. 

This can be done quite seamlessly with overloading the function [`path(string)`](https://github.com/rhaiscript/rhai-fs/blob/11b8af36473c92795ec3b6035bf5612196b0c250/src/path.rs#L9), as every operation must go through this singular function to create a `PathBuf`, unless of course you push a rust defined `PathBuf` to the scope.

**Comment by schungx** [comment]
How does one override `path(string`)` unless you're calling the script version in all your other functions?

The Rust version is compiled in and hard to override.

Youay want to instead take a function callback which the user can provide. Your functions can call this callback to verify or modify a path before doing anything.

**Comment by emesare** [comment]
> How does one override `path(string`)` unless you're calling the script version in all your other functions?

Yes, there is a callback through the engine to the function `path`.
https://github.com/rhaiscript/rhai-fs/blob/11b8af36473c92795ec3b6035bf5612196b0c250/src/file.rs#L74-L82

**Comment by schungx** [comment]
Ah.  Smart in that.

**Comment by dankope** [comment]
Added in commit [9f83e3b](https://github.com/rhaiscript/rhai-fs/commit/9f83e3b335b6305169aa7d9d6234c429d68ff8cf).

**Comment by emesare** [comment]
Added in commit [9f83e3b](https://github.com/rhaiscript/rhai-fs/commit/9f83e3b335b6305169aa7d9d6234c429d68ff8cf).

**Comment by schungx** [comment]
@dankope just find out a problem.  

`ctx.call_fn::<PathBuf>("path", (path_raw,))?; ` will merrily call any implementation of `path`, EVEN IN SCRIPT.

Therefore, any user with `fn path(x) { ... }` in their script can potentially break your API.

We really need a way to call a function in Rhai which is restricted only to Rust functions.  `ctx.call_fn_raw` is close to doing this, but not quite.  I can add a parameter that tells whether script functions are allowed.

A `bool` variable probably should been included in the first place, but `ctx.call_fn_raw` is a public API which I cannot break...

So... I'm adding _yet_ another API to the next version of Rhai:  `ctx.call_native_fn` which will only call native Rust functions (and not scripted ones).

**Comment by schungx** [comment]
@dankope   `call_native_fn` is available in the latest drop.  Pls test out.

**Comment by emesare** [comment]
Added `call_native_fn` in commit https://github.com/rhaiscript/rhai-fs/commit/af9381b2ece1299ba7da083874c73275b0ba92b3.
